use_frameworks!

platform :ios, '10.0'

target 'DucHoangFrameWork_Example' do
  pod 'DucHoangFrameWork', :path => '../'

  target 'DucHoangFrameWork_Tests' do
    inherit! :search_paths

    
  end
end
